name: Lint code and publish Docker image

on:
  push:
    paths:
      # - .github/workflows/lint_and_publish.yml
      - src/bgremover/bgremover.py
      - Dockerfile
  workflow_dispatch:

env:
  LATEST_TAG: sirpersimmon/bgremover:latest

jobs:
  lint-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: true
        tags: ${{ env.LATEST_TAG }}
    
    
      
